export const actionType = {
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGUOT",
    ADD_CIRCLE: "ADD_CIRCLE",
    ADD_RECTANGLE: "ADD_RECTANGLE",
    ADD_LINE: "ADD_LINE",
    CLEAR_ALL: "CLEAR_ALL",
}